apiVersion: apps/v1
kind: Deployment
metadata:
  name: examwizards-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examwizards
  template:
    metadata:
      labels:
        app: examwizards
    spec:
      containers:
        - name: examwizards-container 
          image: abhijeetrane204/examwizards:latest
          ports:
            - containerPort: 3000